// boulding holds for climbing gym
const data = [
  {
    name: 'Jug',
    category: 'Jug',
    hold_type: 'Jug',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#ff00ff', '#00ff00', '#0000ff', '#800080'],
    quantity: 1,
    price: 150,
  },
  {
    name: 'Sloper',
    category: 'Sloper',
    hold_type: 'Sloper',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#00ff00', '#0000ff', '#800080'],
    quantity: 1,
    price: 140,
  },
  {
    name: 'Pinch',
    category: 'Pinch',
    hold_type: 'Pinch',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#ff00ff', '#0000ff', '#800080'],
    quantity: 1,
    price: 150,
  },
  {
    name: 'Crimp',
    category: 'Crimp',
    hold_type: 'Crimp',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#ff00ff', '#00ff00', '#800080'],
    quantity: 1,
    price: 100,
  },
  {
    name: 'Pocket',
    category: 'Pocket',
    hold_type: 'Pocket',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#ff00ff', '#00ff00', '#0000ff'],
    quantity: 1,
    price: 100,
  },
  {
    name: 'Edge',
    category: 'Edge',
    hold_type: 'Edge',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#ff00ff', '#00ff00', '#0000ff', '#800080'],
    quantity: 1,
    price: 150,
  },
  {
    name: 'Volume',
    category: 'Volume',
    hold_type: 'Volume',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#ff00ff', '#00ff00', '#800080'],
    quantity: 1,
    price: 150,
  },
  {
    name: 'Screw On',
    category: 'Screw On',
    hold_type: 'Screw On',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff0000', '#ff00ff', '#00ff00', '#0000ff', '#800080'],
    quantity: 1,
    price: 150,
  },
  {
    name: 'Bolt On',
    category: 'Bolt On',
    hold_type: 'Bolt On',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff00ff', '#00ff00', '#0000ff', '#800080'],
    quantity: 1,
    price: 130,
  },
  {
    name: 'T Nut',
    category: 'T Nut',
    hold_type: 'T Nut',
    material: 'Polyurethane',
    climbing_ability: 'Beginner',
    holds_per_set: 5,
    colors: ['#ff00ff', '#00ff00', '#0000ff', '#800080'],
    quantity: 1,
    price: 130,
  },
]

export default data
